import Head from "next/head";
import Image, { ImageProps } from "next/image";
import styles from "../styles/Home.module.css";

export type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

export type Product = {
  id: string;
  name: string;
  price: string;
  quantity: number;
  created_at: Date;
  updated_at: Date;
};

export interface IPosts {
  posts: Post[];
}

export interface IProducts {
  products: Product[];
}

function Home({ products }: IProducts) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CMS POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ol>
          {products.map((prod) => (
            <li key={prod.id}>
              <div>
                <strong>{prod.name}</strong>
                <br />
                <span>{prod.price}</span>
                <br />
                <span>{prod.quantity}</span>
              </div>
              <br />
            </li>
          ))}
        </ol>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch("http://localhost:3333/products");
  const products: Product = await res.json();

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      products,
    },
  };
}

export default Home;
